import type { PrincipleCard } from "./types.js";

export const PRINCIPLE_CARDS: PrincipleCard[] = [
  {
    id: "P-PRINCIPLE-ACTIVE-RETRIEVAL",
    title: "主动检索适用准则",
    level: "mandatory",
    summary: "每轮任务都必须根据任务情景主动选择适用准则，不依赖用户显式说出准则。",
    appliesTo: ["general", "code_change", "bug_fix", "runtime_issue", "agent_self_correction", "feedback_learning", "research"],
    triggers: ["*"],
    wrongPatterns: ["只在用户明确要求时才应用准则", "把用户纠正当成一次性指令而非可复用准则"],
    requiredActions: ["识别当前任务情景", "选择本轮必须遵守的准则", "将准则以短卡片形式注入 LLM 上下文", "在 trace 中记录激活结果"],
    evaluation: { mustHave: ["principles_selected", "principles_injected"], shouldHave: ["principles_evaluated"] },
  },
  {
    id: "P-ENGINEERING-SOURCE-FIX",
    title: "修改类任务优先源头修复",
    level: "mandatory",
    summary: "修改、bug、异常、优化、纠错类任务必须优先定位源头责任层并做机制修复，不能只做表面规避。",
    appliesTo: ["code_change", "bug_fix", "runtime_issue", "agent_self_correction"],
    triggers: ["修", "改", "bug", "异常", "报错", "失败", "cancel", "cancle", "老是", "不对", "优化", "源头", "根因", "为啥", "为什么"],
    wrongPatterns: ["只解释现象", "只承诺以后避免", "只靠 prompt 约束", "只做 workaround", "没有定位唯一执行入口就修改"],
    requiredActions: ["定位唯一源头入口或责任层", "优先在责任层做代码机制或 guardrail", "保持最小必要改动", "说明防复发机制"],
    evaluation: { mustHave: ["source_entry_identified", "root_fix_or_guardrail", "not_prompt_only"], shouldHave: ["regression_test", "validation_done", "commit_created"] },
  },
  {
    id: "P-RUNTIME-GUARDRAIL",
    title: "Runtime 层必须兜底不可信输入",
    level: "mandatory",
    summary: "LLM output、工具结果和外部输入都不可信；执行层必须做校验、去重、超时、权限和安全边界控制。",
    appliesTo: ["runtime_issue", "agent_self_correction", "bug_fix", "code_change"],
    triggers: ["工具", "tool", "调用", "重复", "parallel", "cancel", "cancle", "超时", "权限", "安全", "执行链路", "runtime", "dispatch"],
    wrongPatterns: ["依赖模型自觉不犯错", "把 runtime 保护只写进 prompt", "工具执行前没有统一校验"],
    requiredActions: ["把防御放到统一执行入口", "对不可信输入做校验和去重", "保留必要 tool_result 以维护会话一致性", "记录 trace 和日志证据"],
    evaluation: { mustHave: ["guardrail_at_runtime_boundary", "invalid_input_handled"], shouldHave: ["trace_recorded", "regression_test"] },
  },
  {
    id: "P-REGRESSION-TEST",
    title: "已发生问题必须有回归测试",
    level: "mandatory",
    summary: "修复已复现或用户反馈的问题时，必须新增或更新 regression test，并运行验证。",
    appliesTo: ["code_change", "bug_fix", "runtime_issue", "agent_self_correction"],
    triggers: ["修", "bug", "回归", "测试", "复现", "失败", "异常", "不对", "老是", "cancel", "cancle"],
    wrongPatterns: ["只手测", "只改代码不加测试", "只跑无关验证"],
    requiredActions: ["新增或更新覆盖该问题的测试", "先跑相关测试", "再跑必要的 typecheck 或全量测试", "报告验证结果"],
    evaluation: { mustHave: ["regression_test", "validation_done"], shouldHave: ["test_failed_before_fix_when_practical"] },
  },
  {
    id: "P-FEEDBACK-LEARNING-LOOP",
    title: "用户纠正必须进入学习闭环",
    level: "mandatory",
    summary: "用户纠正 agent 行为时，必须归因并沉淀为准则、记忆、测试或代码机制，后续由任务情景主动触发。",
    appliesTo: ["feedback_learning", "agent_self_correction"],
    triggers: ["不是", "不应该", "你应该", "纠正", "反馈", "沉淀", "经验", "准则", "守则", "后续", "下次", "流程", "机制", "评价"],
    wrongPatterns: ["只道歉不沉淀", "只保存记忆不接入运行时", "只写文档不加载", "没有评价经验是否被应用"],
    requiredActions: ["提炼可复用准则", "接入主动选择和 prompt 注入", "添加应用评价机制", "把用户反馈保存为 correction memory 或 pending principle"],
    evaluation: { mustHave: ["principle_updated_or_created", "runtime_selection_supported", "application_evaluated"], shouldHave: ["memory_saved", "tests_added"] },
  },
  {
    id: "P-NO-PROMPT-ONLY-FIX",
    title: "系统性问题禁止只靠 Prompt 修复",
    level: "mandatory",
    summary: "系统性问题必须优先考虑代码机制、运行时 guardrail、测试和观测；prompt 只能作为辅助。",
    appliesTo: ["bug_fix", "runtime_issue", "agent_self_correction", "code_change"],
    triggers: ["prompt", "提示词", "尽量", "避免", "系统性", "机制", "源头", "bug", "异常", "工具"],
    wrongPatterns: ["我以后会注意", "我会尽量避免", "只修改提示词", "没有工程兜底"],
    requiredActions: ["判断能否用代码机制消除问题", "不能仅以 prompt 变更作为最终修复", "若只能 prompt 修复，必须说明限制和验证路径"],
    evaluation: { mustHave: ["not_prompt_only", "engineering_fix_considered"], shouldHave: ["guardrail_or_test"] },
  },
];
